### ISSUE TITLE
Accept work workflow

### ISSUE THREAD

**Issue by extsoft** [bees-hive/elegant-git#137]
git checkout -b eg origin/master
git rebase --merge --strategy ff-only ${remote branch}
git checkout master
git merge --ff-only eg
git push origin master:master
git branch -d eg
git push origin --delete ${remote branch}

**Comment by 0pdd** [comment]
@extsoft the puzzle [#146](https://github.com/bees-hive/elegant-git/issues/146) is still not solved.

**Comment by 0pdd** [comment]
@extsoft the only puzzle [#146](https://github.com/bees-hive/elegant-git/issues/146) is solved here.
