### ISSUE TITLE
Please add configurable git precommit hooks for different languages

### ISSUE THREAD

**Issue by vpaslav** [bees-hive/elegant-git#192]
### A problem/task I want to solve
During development cycle it's really great to ensure that badly formatted code or even syntax errors won't be committed into repository and code is covered with unit tests. So, I propose to add precommit git hooks that will run different verifications. For python, for instance, we can run flake8, pytest and coverage. 

### The solution I'd like
During application configuration I would like to see an option for which language I need verifications, what automatically install all necessary tools or propose "how to configure" steps.

**Comment by extsoft** [comment]
@vpaslav thank you for proposing this. 

I would suggest the following flow:
1. Ask a user if a git pre-commit hook is needed
2. If yes, create a "hello world" hook and print some instructions

@vpaslav is it what you are looking for?

**Comment by extsoft** [comment]
@vpaslav Now it's possible to configure custom workflows. So, you can add any hooks you need. Possible, in the future, we are going to add some predefined workflows in a separate repository.

**Comment by vpaslav** [comment]
@extsoft cool, I'll check this feature soon. Thanks.
