### ISSUE TITLE
Fix autocompletion macOS (brew instalation)

### ISSUE THREAD

**Issue by alexbeatnik** [bees-hive/elegant-git#205]
### The bug
Do not work autocompletion when you typping `git-elegant`

### Steps to reproduce
1. `brew install git`
2. `brew install bees-hive/hive/elegant-git`
3. `git-elegant sa{-tab-}`

### My environment
- `git --version`:  2.23.0
- `bash --version`: 3.2.57
-  OS: macOS Mojave

**Comment by extsoft** [comment]
@alexbeatnik please try a new version - https://github.com/bees-hive/elegant-git/releases/tag/0.11.0. It should solve the issue.

**Comment by alexbeatnik** [comment]
@extsoft I try to update elegant git using brew and have this output
`○ → brew upgrade elegant-git
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
Error: bees-hive/hive/elegant-git 0.10.0 already installed`

**Comment by extsoft** [comment]
@alexbeatnik try to uninstall and install again. I think it's related to Brew, not Elegant Git.

**Comment by alexbeatnik** [comment]
> @alexbeatnik try to uninstall and install again. I think it's related to Brew, not Elegant Git.

You are right steps to uninstall and install helps. Autocompletion works

**Comment by alexbeatnik** [comment]
@extsoft
