### ISSUE TITLE
Add autocompletion for "zsh" shell

### ISSUE THREAD

**Issue by vyahello** [bees-hive/elegant-git#230]
### A problem/task I want to solve
I cannot use autocompletion for `elegant-git` tool using `zsh` shell.

### The solution I'd like
I would like `elegant-git` tool autocompletion to work with `zsh` shell the same as it currently works with `bash` shell.

**Comment by extsoft** [comment]
@vyahello thank you for the issue. I'm going to make implementation and will notify you once it will be released.

**Comment by extsoft** [comment]
@vyahello implemented in version `0.17.0`.
