### ISSUE TITLE
Add user-friendly commit logs description 

### ISSUE THREAD

**Issue by vyahello** [bees-hive/elegant-git#231]
### A problem/task I want to solve
I want to see commit messages in an easy and user-friendly way that can display message subject and commit hash such as general `git log --pretty=oneline -5` command works.

### The solution I'd like
Add extra command to `git elegant` tool e.g `git elegant show-work` or `git elegant pretty-log` etc.

**Comment by extsoft** [comment]
@vyahello thank you for the issue. I'm going to make implementation and will notify you once it will be released.

**Comment by extsoft** [comment]
@vyahello Please try a new `show-work` command which is available in version `0.16.0` (https://elegant-git.bees-hive.org/en/0.16.0/commands/#show-work). Does it fit your needs?

**Comment by vyahello** [comment]
Looks great now, thx 👍
