### ISSUE TITLE
Add haskell implementation for aquire-repository command

### ISSUE THREAD

**Issue by teggotic** [bees-hive/elegant-git#297]
The original command is in `./libexec/git-elegant-aquire-repository`.

**Comment by extsoft** [comment]
@teggotic the GPG logic is still pending.

**Comment by teggotic** [comment]
@extsoft I'd like you to merge https://github.com/bees-hive/elegant-git/pull/300 first, as it improves testability and resolves an issue with the already merged aliases setup logic.
