### ISSUE TITLE
git-elegant:159-159: Describe usage of git elegant

### ISSUE THREAD

**Issue by 0pdd** [bees-hive/elegant-git#30]
The puzzle `6-8bd69a57` (from #6) in [`src/main/git-elegant`](https://github.com/extsoft/elegant-git/blob/master/src/main/git-elegant) (lines 159-159) has to be resolved: "Describe usage of git elegant"

The puzzle was created by Dmytro Serdiuk on 22-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by extsoft** [comment]
Duplicates #118
