### ISSUE TITLE
git-elegant-configure:37-37: Add usage message if mandatory...

### ISSUE THREAD

**Issue by 0pdd** [bees-hive/elegant-git#40]
The puzzle `9-dbf97594` (from #9) in [`src/main/git-elegant-configure`](https://github.com/extsoft/elegant-git/blob/master/src/main/git-elegant-configure) (lines 37-37) has to be resolved: "Add usage message if mandatory argument is not set for `git-elegant configure`."

The puzzle was created by Dmytro Serdiuk on 23-Aug-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by extsoft** [comment]
Irrelevant issue.
